// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerData } from "./tables/Player.sol";
import { PlayerIndex } from "./tables/PlayerIndex.sol";
import { PlayerCount } from "./tables/PlayerCount.sol";
import { Tick } from "./tables/Tick.sol";
