// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { System } from "@latticexyz/world/src/System.sol";
import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";
import { PlayerAction } from "../../Types.sol";

/**
 * @title IPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlayerSystem {
  function main__spawn(bytes14 namespace, bytes16 name, System brain) external returns (ResourceId);

  function main__run(PlayerAction action) external;
}
